name: Greeting from Skyler
on: push

jobs:
  my-job:
    name: My Job
    runs-on: self-hosted
    steps:
    - name: Check_file
      id: check_file    
      run: |
        FILE_PATH="/Users/sswang/actions-runner/_work/GithubActionTest/GithubActionTest/README"
        if [ -f "$FILE_PATH" ]; then
            echo "file exists"
            echo "REPO_EXISTS=true" >> $GITHUB_ENV
        else
            echo "file not exists"
            echo "REPO_EXISTS=false" >> $GITHUB_ENV
        fi
    - name: Notifi check result
      if: ${{ env.REPO_EXISTS != true }}
      run: |
        echo "Performing git checkout...$REPO_EXISTS"
    - name: Checkout repo
      if: ${{ env.REPO_EXISTS != true }}
      uses: actions/checkout@v2
      with:
        repository: wangzitao/GithubActionTest
        path: .
    - name: Perform pull if directory exists
      if: ${{ env.REPO_EXISTS == true }}
      run: |
        echo "Performing git pull..."
        git pull
    - name: List file
      run: |
        REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
        ls ~/actions-runner/_work/$REPO_NAME/$REPO_NAME/

