name: Greeting from Skyler
on: push

jobs:
  my-job:
    name: My Job
    runs-on: self-hosted
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there!
        FIRST_NAME: Skyler
        LAST_NAME: Wang
        MY_SECRET: ${{ secrets.SS_SECRETS }}
      run: |
        echo $MY_VAR $FIRST_NAME $LAST_NAME. $MY_SECRET
    - name: Checkout Update latest version
      run: |
        if [ -f "~/actions-runner/_work/GithubActionTest/GithubActionTest/ReadME" ]; then
            echo "File exists, no need to checkout another repo."
            echo "::set-output name=file_exists::true"
        else
            echo "File does not exist, will checkout another repo."
            echo "::set-output name=file_exists::false"
        fi
    - name: Notifi checkout
      if: ${{ steps.check_file.outputs.file_exists != 'true' }}
      run: |
        echo "Performing git checkout..."
    - name: Checkout repository(file does not exist)
      if: ${{ steps.check_file.outputs.file_exists != 'true' }}
      uses: actions/checkout@v2
      with:
        repository: wangzitao/GithubActionTest
        path: repo
    - name: Perform pull if directory exists
      if: steps.check_dir.outputs.dir_exists == 'true'
      run: |
        echo "Performing git pull..."
        git pull
    - name: List file
      run: |
        REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
        ls ~/actions-runner/_work/$REPO_NAME/$REPO_NAME/

