name: Greeting from Skyler
on: push

jobs:
  my-job:
    name: My Job
    runs-on: self-hosted
    steps:
    - name: Check_file
      id: check_file    
      run: |
        FILE_PATH="/Users/sswang/actions-runner/_work/GithubActionTest/GithubActionTest/README"
        if [ -f "$FILE_PATH" ]; then
            echo "file exists"
            echo "##[set-output name=fileExists;value=true]"
        else
            echo "file not exists"
            echo "##[set-output name=fileExists;value=false]"
        fi
    - name: Notifi checkout
      if: ${{ steps.check_file.outputs.fileExists != 'true' }}
      run: |
        echo "Performing git checkout...${{ steps.check_file.outputs.fileExists }}"
    - name: Checkout repo
      if: ${{ steps.check_file.outputs.fileExists != 'true' }}
      uses: actions/checkout@v2
      with:
        repository: wangzitao/GithubActionTest
        path: .
    - name: Perform pull if directory exists
      if: steps.check_dir.outputs.dir_exists == 'true'
      run: |
        echo "Performing git pull..."
        git pull
    - name: List file
      run: |
        REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
        ls ~/actions-runner/_work/$REPO_NAME/$REPO_NAME/

