name: Greeting from Skyler
on: push

jobs:
  my-job:
    name: My Job
    runs-on: macos-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Skyler
        LAST_NAME: Wang
        MY_SECRET: ${{ secrets.SS_SECRETS }}
      run: |
        echo $MY_VAR $FIRST_NAME $LAST_NAME. $MY_SECRET
    - name: Check out code
      uses: actions/checkout@v2
    - name: List file
      run: |
        REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
        ls /Users/runner/work/$REPO_NAME/$REPO_NAME

